<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Features\Auth\Commands\" />
      <Folder Include="Features\Stories\Commands\" />
      <Folder Include="Features\Stories\Queries\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.9" />
      <PackageReference Include="Scrutor" Version="6.1.0" />
    </ItemGroup>

</Project>
