<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Features\Auth\Commands\" />
      <Folder Include="Features\Genres\Commands\" />
      <Folder Include="Features\Genres\Queries\" />
      <Folder Include="Features\Statuses\Commands\" />
      <Folder Include="Features\Statuses\Queries\" />
      <Folder Include="Features\UserProfiles\Commands\" />
      <Folder Include="Features\UserProfiles\Queries\" />
      <Folder Include="Features\Users\Commands\" />
      <Folder Include="Features\Users\Queries\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="10.0.8" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.8" />
      <PackageReference Include="Venly.Dispatch" Version="0.1.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Domain\Domain.csproj" />
    </ItemGroup>

</Project>
